### ISSUE TITLE
能不能增加一个空格暂停键，挺需要的

### ISSUE THREAD

**Issue by 01Petard** [xxxily/h5player#277] opened 2021-07-26 04:44 UTC
1. **问题描述**

2. **出现上述问题的地址**

3. **你使用的浏览器与浏览器版本信息**

4. **其他附注信息**

**Comment by JAGulin** [comment] 2021-09-06 05:28
@01Petard You didn't say what site you have problem with etc. Is it a duplicate of the Bilibili issue above?

**Comment by 01Petard** [comment] 2021-09-07 00:45
Yes, I didn’t see what others said above, sorry to repeat it again. But I have solved it, this plug-in and another plug-in of the same kind are extremely prone to shortcut key conflicts.

**Comment by 01Petard** [comment] 2021-09-07 00:45
> @01Petard You didn't say what site you have problem with etc. Is it a duplicate of the Bilibili issue above?

Yes, I didn’t see what others said above, sorry to repeat it again. But I have solved it, this plug-in and another plug-in of the same kind are extremely prone to shortcut key conflicts.

**Closed** 2022-03-15 14:13 UTC
